(package "kalandralang-mode"
         "0.0.1"
         "")

(website-url "https://github.com/Fuco1/kalandralang-mode")
(keywords "")

(package-file "kalandralang-mode.el")
(files "tests/kalandralang-mode-test-helpers.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source 'melpa)

(depends-on "emacs" "26.1")

(development
 (depends-on "buttercup")
 (depends-on "shut-up"))
